OfficialWebSite: "https://www.openim.io/zh"
DocWebSite: "https://docs.openim.io/zh-Hans/sdks/introduction"
APIAddr: "https://web.openim.io/api"
WsAddr: "wss://web.openim.io/msg_gateway"
DataDir: "cache"
LogFilePath: "cache"
IsLogStandardOutput: false
LogLevel: 5
AdminToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiJpbUFkbWluIiwiUGxhdGZvcm1JRCI6MTAsImV4cCI6MTc1MTI2OTEzNCwiaWF0IjoxNzQzNDkzMTI5fQ.UstdBxy3DXs4F0KZH6_l_Mfbc8rUs2TR_anDUkYJM6E"
# 测试帐户
TestAccounts:
  - UserId: dotnet_test_1
    Token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiJkb3RuZXRfdGVzdF8xIiwiUGxhdGZvcm1JRCI6MywiZXhwIjoxNzUxMjY5MjAwLCJpYXQiOjE3NDM0OTMxOTV9.MUmtkOy8VIFuIcCwyCxpx72LJfUiQiB9ZdTtFla7fZ8"
  - UserId: dotnet_test_2
    Token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiJkb3RuZXRfdGVzdF8yIiwiUGxhdGZvcm1JRCI6MywiZXhwIjoxNzUxMjY5MjE0LCJpYXQiOjE3NDM0OTMyMDl9.FlSdJmAw2upVT8YQeQ7DPMlsTvTeULlnCiZ8eAgPZng"
